---
minimum_pre_commit_version: 2.4.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace   # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer     # Makes sure files end in a newline and only a newline.
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: check-ast             # Simply check whether files parse as valid python.

  # ----- Formatting ---------------------------------------------------------------------------->
  - repo: https://github.com/saltstack/pre-commit-remove-import-headers
    rev: 1.1.0
    hooks:
      - id: remove-import-headers

  - repo: local
    hooks:
      - id: check-cli-examples
        name: Check CLI examples on execution modules
        entry: python .pre-commit-hooks/check-cli-examples.py
        language: system
        files: ^src/saltext/data_remove/modules/.*\.py$

  - repo: local
    hooks:
      - id: check-docs
        name: Check rST doc files exist for modules/states
        entry: python .pre-commit-hooks/make-autodocs.py
        language: system
        pass_filenames: false

  - repo: https://github.com/s0undt3ch/salt-rewrite
    # Automatically rewrite code with known rules
    rev: 1.3.3
    hooks:
      - id: salt-rewrite
        alias: rewrite-docstrings
        name: Salt extensions docstrings auto-fixes
        files: ^src/saltext/data_remove/.*\.py$
        args: [--silent]

  - repo: https://github.com/s0undt3ch/salt-rewrite
    # Automatically rewrite code with known rules
    rev: 1.3.3
    hooks:
      - id: salt-rewrite
        alias: rewrite-tests
        name: Rewrite the test suite
        files: ^tests/.*\.py$
        args: [--silent, -E, fix_docstrings]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.23.3
    hooks:
      - id: pyupgrade
        name: Rewrite Code to be Py3.6+
        args: [
          --py36-plus
        ]
        exclude: src/saltext/data_remove/version.py

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        args: [
          --py3-plus,
        ]
        exclude: src/saltext/data_remove/version.py

  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        args: [-l 100]
        exclude: src/saltext/data_remove/version.py

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        args: [--skip-errors]
        files: ^(docs/.*\.rst|src/saltext/data_remove/.*\.py)$
        additional_dependencies: [black==21.7b0]
  # <---- Formatting -----------------------------------------------------------------------------

  # ----- Security ------------------------------------------------------------------------------>
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
        alias: bandit-salt
        name: Run bandit against the code base
        args: [--silent, -lll, --skip, B701]
        exclude: src/saltext/data_remove/version.py
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
        alias: bandit-tests
        name: Run bandit against the test suite
        args: [--silent, -lll, --skip, B701]
        files: ^tests/.*
  # <---- Security -------------------------------------------------------------------------------

  # ----- Code Analysis ------------------------------------------------------------------------->
  - repo: https://github.com/saltstack/mirrors-nox
    rev: v2021.6.12
    hooks:
      - id: nox
        alias: lint-src
        name: Lint Source Code
        files: ^((setup|noxfile)|src/.*)\.py$
        args:
          - -e
          - lint-code-pre-commit
          - --

  - repo: https://github.com/saltstack/mirrors-nox
    rev: v2021.6.12
    hooks:
      - id: nox
        alias: lint-tests
        name: Lint Tests
        files: ^tests/.*\.py$
        args:
          - -e
          - lint-tests-pre-commit
          - --
  # <---- Code Analysis --------------------------------------------------------------------------

  # ----- Static Test Requirements -------------------------------------------------------------->
  - repo: https://github.com/saltstack/pip-tools-compile-impersonate
    rev: '4.1'
    hooks:
      - id: pip-tools-compile
        alias: compile-3.6-test-requirements
        name: Py3.6 Test Requirements
        files: ^requirements/tests.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.6
          - --platform=linux
          - requirements/tests.in

      - id: pip-tools-compile
        alias: compile-3.7-test-requirements
        name: Py3.7 Test Requirements
        files: ^requirements/tests.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.7
          - --platform=linux
          - requirements/tests.in

      - id: pip-tools-compile
        alias: compile-3.8-test-requirements
        name: Py3.8 Test Requirements
        files: ^requirements/tests.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.8
          - --platform=linux
          - requirements/tests.in

      - id: pip-tools-compile
        alias: compile-3.9-test-requirements
        name: Py3.9 Test Requirements
        files: ^requirements/tests.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.9
          - --platform=linux
          - requirements/tests.in
  # <---- Static Test Requirements ---------------------------------------------------------------

  # ----- Static Lint Requirements -------------------------------------------------------------->
      - id: pip-tools-compile
        alias: compile-3.6-test-requirements
        name: Py3.6 Lint Requirements
        files: ^requirements/lint.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.6
          - --platform=linux
          - requirements/lint.in

      - id: pip-tools-compile
        alias: compile-3.7-test-requirements
        name: Py3.7 Lint Requirements
        files: ^requirements/lint.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.7
          - --platform=linux
          - requirements/lint.in

      - id: pip-tools-compile
        alias: compile-3.8-test-requirements
        name: Py3.8 Lint Requirements
        files: ^requirements/lint.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.8
          - --platform=linux
          - requirements/lint.in

      - id: pip-tools-compile
        alias: compile-3.9-test-requirements
        name: Py3.9 Lint Requirements
        files: ^requirements/lint.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.9
          - --platform=linux
          - requirements/lint.in
  # <---- Static Lint Requirements ---------------------------------------------------------------

  # ----- Static Docs Requirements -------------------------------------------------------------->
      - id: pip-tools-compile
        alias: compile-3.6-test-requirements
        name: Py3.6 Docs Requirements
        files: ^requirements/docs.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.6
          - --platform=linux
          - requirements/docs.in

      - id: pip-tools-compile
        alias: compile-3.7-test-requirements
        name: Py3.7 Docs Requirements
        files: ^requirements/docs.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.7
          - --platform=linux
          - requirements/docs.in

      - id: pip-tools-compile
        alias: compile-3.8-test-requirements
        name: Py3.8 Docs Requirements
        files: ^requirements/docs.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.8
          - --platform=linux
          - requirements/docs.in

      - id: pip-tools-compile
        alias: compile-3.9-test-requirements
        name: Py3.9 Docs Requirements
        files: ^requirements/docs.in$
        pass_filenames: false
        args:
          - -v
          - --py-version=3.9
          - --platform=linux
          - requirements/docs.in
  # <---- Static Docs Requirements ---------------------------------------------------------------
