[build-system]
requires = ["setuptools>=50.3.2", "wheel", "setuptools-declarative-requirements"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/saltext/data_remove/version.py"
write_to_template = "__version__ = \"{version}\""

[tool.black]
line-length = 100
